FROM node:18 as builder

WORKDIR /app

# Copy the server directory containing package.json
COPY ./server ./server

# Install dependencies from the server directory
WORKDIR /app/server
RUN rm -rf node_modules package-lock.json && npm install

EXPOSE 4000

CMD ["node", "index.js"]