name: CI - Build Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build Backend
        working-directory: ./server
        run: |
          npm install
          npm run build

      - name: Install and Build Frontend
        working-directory: ./client
        run: |
          npm install
          npm run build
